Repository ubclaunchpad/inertia, pull requests merged in 2018-06, with the labels that each got.

#220 WebSockets
  Gopkg.lock
  Gopkg.toml
  client/client.go
  client/client_test.go
  client/socket.go
  common/util.go
  common/util_test.go
  daemon/README.md
  daemon/inertiad/daemon.go
  daemon/inertiad/down.go
  daemon/inertiad/log/logger.go
  daemon/inertiad/log/logger_test.go
  daemon/inertiad/log/routine.go
  daemon/inertiad/log/routine_test.go
  daemon/inertiad/log/writers.go
  daemon/inertiad/logger.go
  daemon/inertiad/logger_test.go
  daemon/inertiad/logs.go
  daemon/inertiad/project/build.go
  daemon/inertiad/project/tool.go
  daemon/inertiad/reset.go
  daemon/inertiad/up.go
  deploy.go
Labels: status: ready for review :+1:

#224 Brian/#223 dev proxy
  daemon/inertiad/auth/permissions.go
  daemon/web/client.js
  daemon/web/components/App.js
  daemon/web/components/Dashboard.js
  daemon/web/components/Home.js
  daemon/web/components/Login.js
  daemon/web/index.js
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/webpack.config.js
Labels: area: daemon, area: web, status: ready for review :+1:

#235 Improve travis speed
  .gitignore
  .travis.yml
  Makefile
  daemon/inertiad/project/build.go
  daemon/inertiad/project/docker.go
  daemon/web/package-lock.json
  daemon/web/package.json
  test/docker_deps.sh
  test/lint_deps.sh
Labels: status: work in progress :hammer_and_pick:

#233 frontend setup complete
  daemon/web/.eslintrc.json
  daemon/web/actions/_constants.js
  daemon/web/actions/dashboard.js
  daemon/web/actions/login.js
  daemon/web/actions/main.js
  daemon/web/common/API.js
  daemon/web/components/LogView.js
  daemon/web/index.js
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/pages/app/App.js
  daemon/web/pages/containers/Containers.js
  daemon/web/pages/dashboard/Dashboard.js
  daemon/web/pages/login/Login.js
  daemon/web/pages/main/Main.js
  daemon/web/store/dashboard.js
  daemon/web/store/index.js
  daemon/web/store/login.js
  daemon/web/store/main.js
  daemon/web/styles/colors.sass
  daemon/web/styles/index.sass
  daemon/web/styles/typography.sass
Labels: status: ready for review :+1:

#229 Brian/#133 more git hosts
  common/git.go
  common/git_test.go
  common/util.go
  common/util_test.go
  daemon/inertiad/project/deployment_test.go
  deploy.go
Labels: status: finalized :+1:

#254 Warn if configuration file version doesn't match CLI version
  Makefile
  deploy.go
Labels: status: finalized :+1:

#256 Stream commands by default, add option to use "short" version
  deploy.go
Labels: status: finalized :+1:

#255 Add '--restart unless-stopped' to daemon startup
  client/internal/compiled.go
  client/scripts/daemon-up.sh
Labels: status: finalized :+1:

#257 Add '--verify-ssl' flag to enable certificate verification
  client/client.go
  client/client_test.go
  deploy.go
  env.go
  local/storage.go
  users.go
Labels: status: finalized :+1:

#263 Remove go-git dependencies in CLI
  common/git.go
  common/git_test.go
  deploy.go
  local/git.go
  local/git_test.go
  local/storage.go
  remote.go
Labels: status: finalized :+1:

#264 Roger/243 inertia web terminal view component
  daemon/web/components/TerminalView/TerminalView.js
  daemon/web/pages/containers/Containers.js
Labels: merge: squash, status: finalized :+1:

#267 Fix config send, add --dest flag
  common/request.go
  deploy.go
Labels: status: finalized :+1:

#268 Table component
  daemon/web/.eslintrc.json
  daemon/web/components/Table/Table.js
  daemon/web/components/Table/index.sass
  daemon/web/styles/colors.sass
Labels: merge: squash, status: finalized :+1:

#269 Daemon internal configuration rework
  Dockerfile
  daemon/inertiad/auth/auth.go
  daemon/inertiad/build/builder.go
  daemon/inertiad/build/doc.go
  daemon/inertiad/build/util.go
  daemon/inertiad/cfg/config.go
  daemon/inertiad/cfg/doc.go
  daemon/inertiad/cmd.go
  daemon/inertiad/daemon.go
  daemon/inertiad/project/deploy_test.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/project/deployment_test.go
  daemon/inertiad/up.go
  test/daemon.env
  test/start_local_daemon.sh
Labels: status: finalized :+1:

#270 Deliver file to absolute path on host
  .gitignore
  client/ssh.go
  deploy.go
Labels: status: finalized :+1:

#274 Inertia web terminal view component refactor
  daemon/web/components/TerminalView/TerminalView.js
  daemon/web/components/TerminalView/index.sass
Labels: merge: squash

#275 Allow variable config path via --config flag
  .gitignore
  common/util.go
  config.go
  deploy.go
  env.go
  local/storage.go
  local/storage_test.go
  main.go
  remote.go
  users.go
Labels: merge: squash, status: finalized :+1:

#265 ECS VPS provisioning
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  client/internal/compiled.go
  client/scripts/docker.sh
  common/util.go
  common/util_test.go
  input.go
  local/storage.go
  local/storage_test.go
  provision.go
  provision/doc.go
  provision/ec2.go
  provision/ec2_test.go
Labels: status: finalized :+1:

#282 Map for config.Remotes, add example inertia.toml
  cfg/config.go
  cfg/config_test.go
  cfg/remote.go
  client/client_test.go
  example.inertia.toml
  input.go
  local/storage_test.go
  provision/ec2.go
Labels: merge: squash, status: finalized :+1:

#284 Add fontawesome
  daemon/web/index.html
Labels: merge: squash, status: finalized :+1:

#272 Icon headers
  daemon/web/actions/dashboard.js
  daemon/web/actions/login.js
  daemon/web/actions/main.js
  daemon/web/components/IconHeader/IconHeader.js
  daemon/web/components/IconHeader/index.sass
  daemon/web/pages/containers/Containers.js
  daemon/web/pages/login/Login.js
  daemon/web/styles/typography.sass
Labels: merge: squash

#290 Migrate CLI codebase into package 'cmd'
  .gitignore
  CONTRIBUTING.md
  cmd/README.md
  cmd/config.go
  cmd/deploy.go
  cmd/doc.go
  cmd/env.go
  cmd/format.go
  cmd/format_test.go
  cmd/input.go
  cmd/input_test.go
  cmd/provision.go
  cmd/remote.go
  cmd/root.go
  cmd/users.go
  cmd/util.go
  cmd/util_test.go
  example.inertia.toml
  inertia.go
  inertia_test.go
  main.go
Labels: merge: squash, status: finalized :+1:

#286 Add commit, merge, and branch guidelines
  CONTRIBUTING.md
Labels: merge: squash, status: finalized :+1:

#291 JWT-based authentication rework
  Gopkg.lock
  Makefile
  cmd/provision.go
  daemon/inertiad/auth/auth_test.go
  daemon/inertiad/auth/permissions.go
  daemon/inertiad/auth/permissions_test.go
  daemon/inertiad/auth/sessions.go
  daemon/inertiad/auth/sessions_test.go
  daemon/inertiad/auth/users.go
  daemon/inertiad/auth/users_test.go
  daemon/inertiad/cmd.go
  daemon/inertiad/crypto/authtest.go
  daemon/inertiad/crypto/keys.go
  daemon/inertiad/crypto/keys_test.go
  daemon/inertiad/crypto/token.go
  daemon/inertiad/crypto/token_test.go
  daemon/inertiad/git/error.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/up.go
Labels: status: work in progress :hammer_and_pick:
