Repository ubclaunchpad/inertia, pull requests merged in 2018-05, with the labels that each got.

#195 Windows installation via Scoop
  .travis.yml
  README.md
Labels: status: ready for review :+1:

#196 Faster deploys
  daemon/inertia/project/build.go
  daemon/inertia/project/build_test.go
  daemon/inertia/project/deployment.go
  daemon/inertia/project/deployment_test.go
  daemon/inertia/project/docker.go
Labels: status: ready for review :+1:

#192 #176 querystring (for GET requests)
  client/deployment.go
  client/deployment_test.go
  common/request.go
  daemon/inertia/logs.go
  daemon/web/client.js
  daemon/web/common/encodeURL.js
Labels: status: ready for review :+1:

#191 Modify configuration from CLI
  client/config.go
  client/config_test.go
  init.go
  remote.go
Labels: status: ready for review :+1:

#200 Brian/#199 extract repo name
  common/util.go
  common/util_test.go
  deploy.go
Labels: status: work in progress :hammer_and_pick:

#190 Client package rework
  Makefile
  README.md
  client/README.md
  client/client.go
  client/client_test.go
  client/config.go
  client/config_test.go
  client/deployment.go
  client/remote.go
  client/remote_test.go
  client/ssh.go
  client/ssh_test.go
  daemon/inertia/project/build_test.go
  daemon/web/common/encodeURL.js
  deploy.go
  format.go
  format_test.go
  init.go
  input.go
  input_test.go
  remote.go
  storage.go
  storage_test.go
  test/build/docker-compose/docker-compose.yml
  users.go
Labels: status: ready for review :+1:

#198 John/#188 inertia web linting
  .eslintrc
  Makefile
  daemon/web/.eslintrc.json
  daemon/web/client.js
  daemon/web/common/encodeURL.js
  daemon/web/components/App.js
  daemon/web/components/Dashboard.js
  daemon/web/components/Home.js
  daemon/web/components/Login.js
  daemon/web/components/metrics/LogView.js
  daemon/web/index.js
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/webpack.config.js
  daemon/web/webpack.prod.js
Labels: status: ready for review :+1:

#208 John/#189 styling preprocessor
  daemon/web/index.js
  daemon/web/index.sass
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/webpack.config.js
  daemon/web/webpack.prod.js
Labels: area: web, status: ready for review :+1:

#211 Fix undefined error for PropTypes
  daemon/web/components/metrics/LogView.js
Labels: area: web, status: ready for review :+1:

#212 Improved setup and contribution guide
  .github/CONTRIBUTING.md
  Makefile
  README.md
Labels: status: ready for review :+1:

#213 Bugfixes (v0.4.0-rc1)
  .dockerignore
  Dockerfile
  client/client.go
  client/client_test.go
  daemon/web/package-lock.json
  daemon/web/package.json
  remote.go
Labels: status: ready for review :+1:

#217 Local Test Daemon
  .github/CONTRIBUTING.md
  .gitignore
  Dockerfile
  Makefile
  client/bootstrap.go
  client/bootstrap/token.sh
  daemon/README.md
  daemon/inertiad/auth/auth.go
  daemon/inertiad/auth/auth_test.go
  daemon/inertiad/auth/certificate.go
  daemon/inertiad/auth/certificate_test.go
  daemon/inertiad/auth/password.go
  daemon/inertiad/auth/password_test.go
  daemon/inertiad/auth/permissions.go
  daemon/inertiad/auth/permissions_test.go
  daemon/inertiad/auth/sessions.go
  daemon/inertiad/auth/users.go
  daemon/inertiad/auth/users_test.go
  daemon/inertiad/cmd.go
  daemon/inertiad/daemon.go
  daemon/inertiad/down.go
  daemon/inertiad/down_test.go
  daemon/inertiad/logger.go
  daemon/inertiad/logger_test.go
  daemon/inertiad/logs.go
  daemon/inertiad/mock_test.go
  daemon/inertiad/project/build.go
  daemon/inertiad/project/build_test.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/project/deployment_test.go
  daemon/inertiad/project/docker.go
  daemon/inertiad/project/git.go
  daemon/inertiad/project/git_test.go
  daemon/inertiad/reset.go
  daemon/inertiad/status.go
  daemon/inertiad/status_test.go
  daemon/inertiad/up.go
  daemon/inertiad/webhook.go
  test/start_local_daemon.sh
  test/start_vps.sh
Labels: status: ready for review :+1:

#221 GoDocs
  README.md
  client/README.md
  daemon/README.md
  daemon/inertiad/cmd.go
  daemon/inertiad/doc.go
  doc.go
Labels: status: ready for review :+1:
