Repository ubclaunchpad/inertia, pull requests merged in 2018-07, with the labels that each got.

#294 Replace stdout prints with FPrint to set writers
  client/client.go
  client/client_test.go
  cmd/deploy.go
  cmd/env.go
  cmd/provision.go
  cmd/users.go
  common/util.go
  local/storage.go
  local/storage_test.go
  provision/ec2.go
Labels: merge: squash, pr: finalized :+1:

#299 Correct invalid references and add more detail to guide
  CONTRIBUTING.md
Labels: merge: squash, pr: finalized :+1:

#313 Add missing newlines to clean up bootstrap output
  client/client.go
Labels: area: client, merge: squash, pr: finalized :+1:

#314 inertia [remote] remove
  client/client.go
  client/internal/compiled.go
  client/scripts/daemon-down.sh
  client/scripts/inertia-down.sh
  cmd/config.go
  cmd/deploy.go
  cmd/env.go
  cmd/provision.go
  cmd/remote.go
  cmd/users.go
Labels: pr: finalized :+1:

#295 Image pruning
  client/client.go
  client/client_test.go
  cmd/deploy.go
  cmd/input_test.go
  cmd/provision.go
  daemon/inertiad/build/builder.go
  daemon/inertiad/build/builder_test.go
  daemon/inertiad/cfg/config_test.go
  daemon/inertiad/containers/containers.go
  daemon/inertiad/containers/containers_test.go
  daemon/inertiad/daemon.go
  daemon/inertiad/mock_test.go
  daemon/inertiad/project/deploy_test.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/project/deployment_test.go
  daemon/inertiad/prune.go
  daemon/inertiad/up.go
Labels: pr: finalized :+1:

#317 Report coverage to codecov.io
  .travis.yml
Labels: merge: squash, pr: finalized :+1:

#319 Add coverage configuration
  .codecov.yml
Labels: merge: squash, pr: finalized :+1:

#318 Switch from go-bindata to fileb0x
  CONTRIBUTING.md
  Makefile
  b0x.yml
  client/client.go
  client/internal/compiled.go
Labels: merge: squash, pr: finalized :+1:

#316 Clean up tooltips for consistency
  cmd/config.go
  cmd/deploy.go
  cmd/env.go
  cmd/provision.go
  cmd/remote.go
  cmd/root.go
  cmd/users.go
  daemon/inertiad/cmd.go
  daemon/inertiad/git/error.go
  daemon/inertiad/project/deployment.go
  doc.go
Labels: merge: squash, pr: finalized :+1:

#321 Created different versions of inertia logo
  daemon/web/assets/logo/inertia-horizontal-black.png
  daemon/web/assets/logo/inertia-horizontal-white.png
  daemon/web/assets/logo/inertia-horizontal.png
  daemon/web/assets/logo/inertia-vertical.png
Labels: merge: squash, pr: finalized :+1:

#289 Inertia web settings page
  daemon/web/components/IconHeader/IconHeader.js
  daemon/web/components/PruneImageButton/PruneImageButton.js
  daemon/web/components/PruneImageButton/index.sass
  daemon/web/components/ShutdownButton/ShutdownButton.js
  daemon/web/components/ShutdownButton/index.sass
  daemon/web/pages/main/Main.js
  daemon/web/pages/settings/Settings.js
Labels: merge: squash, pr: work in progress :hammer_and_pick:

#302 Container status
  daemon/web/actions/dashboard.js
  daemon/web/actions/login.js
  daemon/web/actions/main.js
  daemon/web/components/Status/Status.js
  daemon/web/components/Status/index.sass
  daemon/web/pages/containers/Containers.js
  daemon/web/pages/containers/index.sass
  daemon/web/pages/main/Main.js
Labels: merge: squash, pr: finalized :+1:

#325 Webhook support for Bitbucket and Dockerhub
  daemon/inertiad/webhook.go
  daemon/inertiad/webhook/bitbucket.go
  daemon/inertiad/webhook/bitbucket_push.go
  daemon/inertiad/webhook/bitbucket_test.go
  daemon/inertiad/webhook/docker.go
  daemon/inertiad/webhook/docker_test.go
  daemon/inertiad/webhook/github.go
  daemon/inertiad/webhook/github_push.go
  daemon/inertiad/webhook/github_test.go
  daemon/inertiad/webhook/gitlab.go
  daemon/inertiad/webhook/gitlab_push.go
  daemon/inertiad/webhook/gitlab_test.go
  daemon/inertiad/webhook/webhook.go
  daemon/inertiad/webhook/webhook_test.go
Labels: pr: finalized :+1:

#333 Launchpad logo svg
  daemon/web/assets/logo/launchpad-logo-light-blue-01.svg
Labels: merge: squash

#332 added inline svg processing to config
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/webpack.config.js
Labels: merge: squash

#327 Created Footer for web app
  daemon/web/components/Footer/Footer.js
  daemon/web/components/Footer/index.sass
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/pages/main/Main.js
  daemon/web/styles/colors.sass
  daemon/web/styles/typography.sass
  daemon/web/webpack.config.js
  daemon/web/webpack.prod.js
Labels: merge: squash
