Repository ubclaunchpad/inertia, pull requests merged in 2018-03, with the labels that each got.

#100 Build binaries and Docker images on Travis Jobs
  .gitignore
  .scripts/release.sh
  .travis.yml
  Makefile
  common/util_test.go
Labels: :+1: ready for review, :hammer_and_pick: work in progress

#104 Branch deployment
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile
  client/deploy.go
  client/deploy_test.go
  client/remote.go
  common/types.go
  common/util.go
  daemon/docker.go
  daemon/handler.go
  daemon/helper.go
  main.go
  remote.go
  remote_test.go
Labels: :+1: ready for review

#106 Inertia daemon versioning
  .scripts/release.sh
  .travis.yml
  Dockerfile
  Makefile
  README.md
  client/bootstrap.go
  client/bootstrap/daemon-up.sh
  client/bootstrap/token.sh
  client/remote.go
  client/remote_test.go
  daemon.go
  daemon/handler.go
  init.go
  main.go
Labels: :+1: ready for review

#115 Amazon ECS support
  .dockerignore
  .gitignore
  .travis.yml
  Makefile
  README.md
  client/bootstrap.go
  client/bootstrap/docker.sh
  test_env/Dockerfile.amazon
  test_env/Dockerfile.centos
  test_env/startvps.sh
Labels: :hammer_and_pick: work in progress

#113 Fix repository updating, common package refactor
  .dockerignore
  .gitignore
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  client/bootstrap.go
  client/bootstrap/docker.sh
  client/deployment.go
  client/deployment_test.go
  common/git.go
  common/git_test.go
  common/request.go
  common/util.go
  common/util_test.go
  daemon.go
  daemon/auth.go
  daemon/auth_test.go
  daemon/docker.go
  daemon/down.go
  daemon/github.go
  daemon/github_test.go
  daemon/handler.go
  daemon/logs.go
  daemon/reset.go
  daemon/server.go
  daemon/status.go
  daemon/up.go
  deployment.go
  remote.go
  test_env/Dockerfile.amazon
  test_env/Dockerfile.centos
  test_env/startvps.sh
Labels: :+1: ready for review

#122 HTTPS, SSH sessions, refactoring
  Gopkg.lock
  Gopkg.toml
  Makefile
  client/bootstrap.go
  client/bootstrap/daemon-up.sh
  client/config.go
  client/deployment.go
  client/deployment_test.go
  client/remote.go
  client/remote_test.go
  client/ssh.go
  client/ssh_test.go
  daemon.go
  daemon/certificate.go
  daemon/certificate_test.go
  daemon/server.go
  deployment.go
  remote.go
  remote_test.go
Labels: :+1: ready for review

#125 Daemon repackaging
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile
  Makefile
  client/bootstrap.go
  client/bootstrap/daemon-up.sh
  client/bootstrap/token.sh
  common/request.go
  daemon.go
  daemon/inertia/auth.go
  daemon/inertia/auth_test.go
  daemon/inertia/certificate.go
  daemon/inertia/certificate_test.go
  daemon/inertia/daemon.go
  daemon/inertia/docker.go
  daemon/inertia/down.go
  daemon/inertia/github.go
  daemon/inertia/github_test.go
  daemon/inertia/logger.go
  daemon/inertia/logger_test.go
  daemon/inertia/logs.go
  daemon/inertia/main.go
  daemon/inertia/reset.go
  daemon/inertia/status.go
  daemon/inertia/up.go
  remote.go
Labels: :+1: ready for review

#126 Inertia Web scaffold
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  client/bootstrap.go
  daemon/inertia/daemon.go
  daemon/web/client.js
  daemon/web/components/App.js
  daemon/web/index.html
  daemon/web/index.js
  daemon/web/package-lock.json
  daemon/web/package.json
  daemon/web/webpack.config.js
  daemon/web/webpack.prod.js
Labels: :+1: ready for review

#92 Define project name on docker-compose
  client/bootstrap.go
  client/deployment.go
  client/deployment_test.go
  common/request.go
  daemon/inertia/project/docker.go
  daemon/inertia/up.go
  daemon/inertia/webhook.go
  deployment.go
Labels: :hammer_and_pick: work in progress

#135 Roger/#72 merge inertia remote status
  deployment.go
  remote.go
Labels: :+1: ready for review

#138 Allow user to set secret
  client/deployment.go
  client/deployment_test.go
  client/remote.go
  common/request.go
  daemon/inertia/daemon.go
  daemon/inertia/up.go
  daemon/inertia/webhook.go
  deploy_cmd.go
  init_cmd.go
  remote_cmd.go
  remote_cmd_test.go
Labels: :+1: ready for review
