Repository ubclaunchpad/inertia, pull requests merged in 2018-08, with the labels that each got.

#345 Don't reassign deployment
  daemon/inertiad/reset.go
Labels: merge: squash, pr: finalized :+1:

#344 Prompt for input for build config, update msgNoDeployment remote var
  cmd/format.go
  cmd/input.go
  daemon/inertiad/build/builder_test.go
Labels: merge: squash, pr: finalized :+1:

#347 Create Client from ENV and negotiate API version from there
  daemon/inertiad/containers/docker.go
  daemon/inertiad/containers/docker_test.go
Labels: merge: squash, pr: finalized :+1:

#346 Recreate env bucket upon deleting
  daemon/inertiad/project/data.go
  daemon/inertiad/project/data_test.go
Labels: merge: squash, pr: finalized :+1:

#360 Implement favicon
  daemon/web/assets/logo/favicon.ico
  daemon/web/index.html
  daemon/web/webpack.config.js
Labels: merge: squash, pr: finalized :+1:

#356 Dockerfile ports, containerstop fixes, minor updates
  daemon/inertiad/build/builder.go
  daemon/inertiad/build/output.go
  daemon/inertiad/containers/containers.go
  daemon/inertiad/containers/containers_test.go
  daemon/inertiad/log/logger.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/prune.go
Labels: pr: finalized :+1:

#357 Add newlines to ec2 provision output and refactor logic
  provision/ec2.go
Labels: merge: squash, pr: finalized :+1:

#355 Add option to load AWS credentials from file
  cmd/provision.go
  provision/ec2.go
  provision/ec2_test.go
Labels: merge: squash, pr: finalized :+1:

#359 #244 Dashboard Changes
  daemon/web/actions/_constants.js
  daemon/web/actions/dashboard.js
  daemon/web/components/Table/Table.js
  daemon/web/components/Table/index.sass
  daemon/web/pages/dashboard/Dashboard.js
  daemon/web/pages/main/Main.js
  daemon/web/store/dashboard.js
Labels: pr: finalized :+1:

#363 Exit properly if image build fails
  daemon/inertiad/build/builder.go
  daemon/inertiad/build/builder_test.go
  test/build/dockerfile/fail.Dockerfile
Labels: pr: finalized :+1:

#366 Codecov fixes
  codecov.yml
Labels: pr: finalized :+1:

#368 Inject version var directly into package cmd
  .scripts/release.sh
  .travis.yml
  Makefile
  cmd/deploy.go
  cmd/root.go
  inertia.go
  inertia_test.go
Labels: merge: squash, pr: finalized :+1:

#371 Set active to false before stopping containers
  daemon/inertiad/project/deployment.go
Labels: merge: squash, pr: finalized :+1:

#373 Update dependencies
  Gopkg.lock
  Gopkg.toml
Labels: merge: squash, pr: finalized :+1:

#372 Add flag to set lines of logs to fetch
  client/client.go
  client/client_test.go
  cmd/deploy.go
  common/request.go
  daemon/inertiad/containers/containers.go
  daemon/inertiad/containers/containers_test.go
  daemon/inertiad/logs.go
Labels: merge: squash, pr: finalized :+1:

#378 Reduce webhook output
  daemon/inertiad/webhook.go
  daemon/inertiad/webhook/bitbucket_push.go
  daemon/inertiad/webhook/github_push.go
  daemon/inertiad/webhook/gitlab_push.go
  daemon/inertiad/webhook/webhook.go
  daemon/inertiad/webhook/webhook_test.go
Labels: merge: squash, pr: finalized :+1:

#382 Bugfixes
  client/client.go
  client/client_test.go
  cmd/deploy.go
  common/git.go
  common/git_test.go
  common/util_test.go
  daemon/inertiad/git/git.go
  daemon/inertiad/logs.go
  daemon/inertiad/webhook.go
Labels: pr: finalized :+1:

#385 Uploaded Inertia word logo svg
  daemon/web/assets/logo/inertia-logo-word.svg
Labels: merge: squash, pr: finalized :+1:

#384 Global style classes, reworked Table and Footer styles
  daemon/web/.sass-lint.yml
  daemon/web/README.md
  daemon/web/components/Footer/index.js
  daemon/web/components/Footer/index.sass
  daemon/web/components/IconHeader/index.js
  daemon/web/components/IconHeader/index.sass
  daemon/web/components/LogView/index.sass
  daemon/web/components/Status/index.js
  daemon/web/components/Status/index.sass
  daemon/web/components/Table/index.js
  daemon/web/components/Table/index.sass
  daemon/web/components/TerminalView/index.js
  daemon/web/components/TerminalView/index.sass
  daemon/web/components/buttons/PruneImageButton/index.js
  daemon/web/components/buttons/ShutdownButton/index.js
  daemon/web/components/buttons/index.sass
  daemon/web/components/index.sass
  daemon/web/index.html
  daemon/web/pages/App/index.sass
  daemon/web/pages/Containers/index.js
  daemon/web/pages/Containers/index.sass
  daemon/web/pages/Dashboard/index.sass
  daemon/web/pages/Login/index.sass
  daemon/web/pages/Main/index.sass
  daemon/web/pages/Settings/index.sass
  daemon/web/pages/index.sass
  daemon/web/styles/animation.sass
  daemon/web/styles/colors.sass
  daemon/web/styles/decoration.sass
  daemon/web/styles/index.sass
  daemon/web/styles/spacing.sass
  daemon/web/styles/typography.sass
  daemon/web/styles/utils.sass
Labels: pr: finalized :+1:

#386 Run all dep ensure commands with -v flag
  .appveyor.yml
  .travis.yml
  Dockerfile
  Makefile
Labels: merge: squash, pr: finalized :+1:

#388 Disable git branch test on CI, remove Appveyor workaround
  .appveyor.yml
  local/git_test.go
Labels: merge: squash, pr: finalized :+1:

#387 Deprecate Herokuish builds
  Dockerfile
  README.md
  cmd/config.go
  cmd/input.go
  cmd/input_test.go
  common/util.go
  common/util_test.go
  daemon/inertiad/build/builder.go
  daemon/inertiad/build/builder_test.go
  daemon/inertiad/cfg/config.go
  daemon/inertiad/containers/containers_test.go
  daemon/inertiad/daemon.go
  test/daemon.env
  test/docker_deps.sh
Labels: merge: squash, pr: finalized :+1:

#391 API cleanup
  client/client.go
  client/client_test.go
  common/api.go
  common/types.go
  daemon/inertiad/auth/permissions.go
  daemon/inertiad/auth/permissions_test.go
  daemon/inertiad/daemon.go
  daemon/inertiad/down_test.go
  daemon/inertiad/project/deployment.go
  daemon/inertiad/project/deployment_test.go
  daemon/inertiad/util/util.go
  daemon/inertiad/util/util_test.go
  daemon/inertiad/webhook.go
Labels: pr: finalized :+1:

#401 Logout button on Nav
  daemon/web/components/NavBar/index.js
  daemon/web/components/buttons/LogoutButton/index.js
Labels: merge: squash
